apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: platform-changelog-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: platform-changelog-go
    app.kubernetes.io/part-of: platform-changelog-go
  name: platform-changelog-goo5el
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: platform-changelog-go
    weight: 100
status: {}
